In [ ]:

import pandas as pd

data = pd.read_csv("Dengue.csv")
data.head()

         Date Data
0  12/28/2013  244
1  12/29/2013  NaN
2  12/30/2013  NaN
3  12/31/2013  NaN
4    1/1/2014  NaN

In [ ]:

# Convert the 'Date' column to datetime format
data['Date'] = pd.to_datetime(data['Date'], errors='coerce')

# Identify rows with non-NaN data values
weekly_data = data.dropna(subset=['Data'])

weekly_data

           Date Data
0    2013-12-28  244
7    2014-01-04  193
14   2014-01-11  299
21   2014-01-18  200
28   2014-01-25  142
...         ...  ...
2520 2020-11-21   12
2527 2020-11-28   17
2534 2020-12-05    6
2541 2020-12-12   39
2548 2020-12-19   30

[365 rows x 2 columns]

In [ ]:

import pandas as pd


data = pd.read_csv("Dengue.csv")

# Step 1: Convert the 'Date' column to datetime format
data['Date'] = pd.to_datetime(data['Date'], errors='coerce')

# Step 2: Convert the 'Data' column to numeric, forcing non-numeric values to NaN
data['Data'] = pd.to_numeric(data['Data'], errors='coerce')

# Step 3: Create a complete date range
start_date = data['Date'].min()
end_date = data['Date'].max()
date_range = pd.date_range(start=start_date, end=end_date, freq='D')

# Step 4: Reindex the original data to the complete date range
daily_data = data.set_index('Date').reindex(date_range).rename_axis('Date').reset_index()

# Step 5: Fill the missing 'Data' values using forward fill method
daily_data['Data'] = daily_data['Data'].fillna(method='ffill')

# Step 6: Evenly distribute the weekly values over 7 days
daily_data['Data'] = daily_data['Data'] / 7

# Display the first few rows of the daily data
print(daily_data.head(20))

         Date       Data
0  2013-12-28  34.857143
1  2013-12-29  34.857143
2  2013-12-30  34.857143
3  2013-12-31  34.857143
4  2014-01-01  34.857143
5  2014-01-02  34.857143
6  2014-01-03  34.857143
7  2014-01-04  27.571429
8  2014-01-05  27.571429
9  2014-01-06  27.571429
10 2014-01-07  27.571429
11 2014-01-08  27.571429
12 2014-01-09  27.571429
13 2014-01-10  27.571429
14 2014-01-11  42.714286
15 2014-01-12  42.714286
16 2014-01-13  42.714286
17 2014-01-14  42.714286
18 2014-01-15  42.714286
19 2014-01-16  42.714286

In [ ]:
import pandas as pd


data = pd.read_csv("Dengue set1.csv")

data['Date'] = pd.to_datetime(data['Date'], errors='coerce')

# Step 2: Convert the 'Data' column to numeric, forcing non-numeric values to NaN
data['Dengue Data'] = pd.to_numeric(data['Dengue Data'], errors='coerce')

# Step 3: Create a complete date range
start_date = data['Date'].min()
end_date = data['Date'].max()
date_range = pd.date_range(start=start_date, end=end_date, freq='D')

# Step 4: Reindex the original data to the complete date range
daily_data = data.set_index('Date').reindex(date_range).rename_axis('Date').reset_index()

# Step 5: Fill the missing 'Data' values using forward fill method
daily_data['Dengue Data'] = daily_data['Dengue Data'].fillna(method='ffill')

# Step 6: Evenly distribute the weekly values over 7 days
daily_data['Dengue Data'] = daily_data['Dengue Data'] / 7

# Display the first few rows of the daily data
print(daily_data.head(20))

         Date  Dengue Data  Temperature  Dew Point©  Humidity  Precipitation
0  2014-01-01    34.857143         27.8        20.4      66.0            0.0
1  2014-01-02    34.857143         27.4        21.3      70.3            0.0
2  2014-01-03    34.857143         27.0        21.8      73.8            0.0
3  2014-01-04    34.857143         26.9        20.0      66.0            0.0
4  2014-01-05    34.857143         26.1        20.6      71.5            0.0
5  2014-01-06    34.857143         26.6        22.4      77.3            0.0
6  2014-01-07    34.857143         26.5        23.3      83.8            0.0
7  2014-01-08    27.571429         27.6        23.3      78.8            0.0
8  2014-01-09    27.571429         28.2        23.3      76.8            0.0
9  2014-01-10    27.571429         26.4        22.7      80.9            0.0
10 2014-01-11    27.571429         26.7        22.6      78.7            0.0
11 2014-01-12    27.571429         25.4        22.6      83.5            0.0
12 2014-01-13    27.571429         26.9        22.1      77.0            0.0
13 2014-01-14    27.571429         27.0        23.1      67.8            0.0
14 2014-01-15    42.714286         25.9        23.3      87.0            0.0
15 2014-01-16    42.714286         25.4        22.9      87.8            0.0
16 2014-01-17    42.714286         27.1        21.1      70.5            0.0
17 2014-01-18    42.714286         26.4        21.9      75.7            0.0
18 2014-01-19    42.714286         26.6        20.8      71.6            0.0
19 2014-01-20    42.714286         27.1        20.8      68.9            0.0

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
daily_data.head()

        Date  Dengue Data  Temperature  Dew Point©  Humidity  Precipitation
0 2014-01-01    34.857143         27.8        20.4      66.0            0.0
1 2014-01-02    34.857143         27.4        21.3      70.3            0.0
2 2014-01-03    34.857143         27.0        21.8      73.8            0.0
3 2014-01-04    34.857143         26.9        20.0      66.0            0.0
4 2014-01-05    34.857143         26.1        20.6      71.5            0.0

In [ ]:
daily_data.shape

(3652, 6)

In [ ]:
daily_data = daily_data.dropna()

In [ ]:
daily_data.head()

        Date  Dengue Data  Temperature  Dew Point©  Humidity  Precipitation
0 2014-01-01    34.857143         27.8        20.4      66.0            0.0
1 2014-01-02    34.857143         27.4        21.3      70.3            0.0
2 2014-01-03    34.857143         27.0        21.8      73.8            0.0
3 2014-01-04    34.857143         26.9        20.0      66.0            0.0
4 2014-01-05    34.857143         26.1        20.6      71.5            0.0

In [ ]:
y = daily_data['Dengue Data']
x = daily_data[['Temperature', 'Humidity','Precipitation']]

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(x ,y, test_size = 0.1)

In [ ]:
scale = StandardScaler()

X_train = scale.fit_transform(X_train)
X_test = scale.fit_transform(X_test)

##Linear Regression

In [ ]:
linear = LinearRegression()

In [ ]:
model = linear.fit(X_train, Y_train)

In [ ]:
model_pred = model.score(X_test, Y_test)
model_pred

0.0030852117149759994

##KNN

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor(n_neighbors=5)

In [ ]:
model_3 = knn.fit(X_train, Y_train)

In [ ]:
model_pred_3 = model_3.score(X_test, Y_test)
model_pred_3

-0.17393396202604605

##Random forest

In [ ]:
from sklearn.ensemble import RandomForestRegressor

rfr = RandomForestRegressor(n_estimators=30)

In [ ]:
model_5 = rfr.fit(X_train, Y_train)

In [ ]:
model_pred_5 = model_5.score(X_test, Y_test)
model_pred_5

-0.29065507722414896